[package]
name = "mobile-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smoldot = { version = "0.2.0", path = "../..", default-features = false }
smoldot-light-base = { version = "0.1.0", path = "../light-base" }
nix = "0.24.2"
tokio = { version = "1.20.0", features = ["full"] }
futures = "0.3.21"